#!/bin/bash
# runs double and single spin analyses, and draws output
# for even run numbers and for odd run numbers
# FILTERS OUT PROBLEMATIC REGION
touch three.png
rm three.png
root -b -q -l 'Asym3.C('\"pi0\"','\"runeven\"')'
root -b -q -l 'DrawThree.C('\"pi0\"')'
mv -v spin{,_even}.root
mv -v three{,_even}.png
root -b -q -l 'Asym3.C('\"pi0\"','\"runodd\"')'
root -b -q -l 'DrawThree.C('\"pi0\"')'
mv -v spin{,_odd}.root
mv -v three{,_odd}.png
