#!/bin/bash
# produces asymmetry plots for webpage for desired RP trigger

printstatus()
{
  sep="-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
  echo ""
  echo "$sep"
  echo "> > > > > RP_SELECT = $RP_SELECT < < < < <"
  echo "PT_BINS=$PT_BINS EN_BINS=$EN_BINS" 
  echo "PT_DIV_0=$PT_DIV_0 EN_DIV_0=$EN_DIV_0"
  echo "$sep"
  echo ""
}


phibins=10


if [ $# -ne 1 ]; then
  echo "usage: $0 [RP BOOLEAN NAME]"
  exit
fi
RP=$1

# en-dependence
root -b -q Bin_Splitter.C'('${phibins}',1,1,0)'
source env_bins.sh
export RP_SELECT=$RP
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_NEW_BY_SCI_en_$RP



# pt-dependence
root -b -q Bin_Splitter.C'('${phibins}',1,0,1)'
source env_bins.sh
export RP_SELECT=$RP
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_NEW_BY_SCI_pt_$RP


##### EXIT PREMATURELY
exit
######################




######################


# en-dependence for 3 pt regions
root -b -q Bin_Splitter.C'('${phibins}',1,1,0)'
source env_bins.sh
export RP_SELECT=$RP
export PT_DIV_0=0
export PT_DIV_1=3.3
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_collab_en_lowpt_$RP
export PT_DIV_0=3.3
export PT_DIV_1=6.7
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_collab_en_midpt_$RP
export PT_DIV_0=6.7
export PT_DIV_1=10
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_collab_en_highpt_$RP

# pt-dependence for 3 en regions
root -b -q Bin_Splitter.C'('${phibins}',1,0,1)'
source env_bins.sh
export RP_SELECT=$RP
export EN_DIV_0=0
export EN_DIV_1=33.3
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_collab_pt_lowen_$RP
export EN_DIV_0=33.3
export EN_DIV_1=66.7
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_collab_pt_miden_$RP
export EN_DIV_0=66.7
export EN_DIV_1=100
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_collab_pt_highen_$RP
