#!/bin/bash
if [ $# -ne 1 ]; then
  echo "usage: $0 [dir name] in asym_plots/output_[dirname]_*"
  exit
fi
dirname="$1"

#analyse3 N $dirname
analyse3 EOR $dirname
analyse3 WOR $dirname
analyse3 SDE $dirname
analyse3 SDW $dirname
analyse3 IT $dirname
analyse3 ET $dirname
#analyse3 DD $dirname
