// defines binning that is needed in the analysis
//
// all the binning is controlled by the variables in the section CONTROL VARIABLES
// -- low = lower bound
// -- high = upper bound
// -- bins = number of bins 
//    -- if bins=0, then a manually defined binning scheme is used (defined in the code
//       below)
//
// -- these bins do not define the final kinematic cuts used for the jet types; the 
//    final kinematic boundaries are set in PhiDists3.C (and additionally Diagnostics.C)

void Bin_Splitter(Int_t phi_bins = 10,
                  Int_t eta_bins = 1,
                  Int_t pt_bins = 1,
                  Int_t en_bins = 0
)
{
  // CONTROL VARIABLES

  // trigger
  char trigger[16]; strcpy(trigger,"All");

  // en or pt dependent mass cuts
  char cut_type[16]; strcpy(cut_type,"en");

  Double_t phi_low=-3.15;
  Double_t phi_high=3.15;

  Double_t eta_low=2.5;
  Double_t eta_high=4.2; // can go up to 4.5, but do we trust the edge data?

  Double_t pt_low=0.0;   // lowest acceptable pT for runs 12 & 13; hard kin. cutoff overrides this
  Double_t pt_high=10.0; // pi0 reconstruction is unreliable for pT>15

  Double_t en_low=0.0; // E>30 cutoff point for pi0s; should allow sph & thr to go lower
  Double_t en_high=100; // can go up to 255, but cluster merging for pi0s is problem for E>100

  char efile[64];
  strcpy(efile,"env_bins.sh");

  gSystem->RedirectOutput(efile,"w");
  printf("#!/bin/bash\n");
  printf("# This file was generated by Bin_Splitter.C\n");
  printf("# ** source this file while in this directory\n\n");
  printf("export SPINDIR=$(pwd)\n");


  // phi
  printf("\nexport PHI_LOW=%f\n",phi_low);
  printf("export PHI_HIGH=%f\n",phi_high);
  Double_t phi_width;
  if(phi_bins>0)
  {
    printf("export PHI_BINS=%d\n",phi_bins);
    phi_width = (phi_high-phi_low)/phi_bins;
    for(Int_t i=0; i<=phi_bins; i++) printf("export PHI_DIV_%d=%f\n",i,phi_low+i*phi_width);
  }
  else
  {
    phi_bins=1;
    printf("export PHI_BINS=%d\n",phi_bins);
    printf("export PHI_DIV_0=%f\n",phi_low);
    printf("export PHI_DIV_1=%f\n",phi_high);
  };


  // eta
  printf("\nexport ETA_LOW=%f\n",eta_low);
  printf("export ETA_HIGH=%f\n",eta_high);
  Double_t eta_width;
  if(eta_bins>0)
  {
    printf("export ETA_BINS=%d\n",eta_bins);
    eta_width = (eta_high-eta_low)/eta_bins;
    for(Int_t i=0; i<=eta_bins; i++) printf("export ETA_DIV_%d=%f\n",i,eta_low+i*eta_width);
  }
  else
  {
    eta_bins=1;
    printf("export ETA_BINS=%d\n",eta_bins);
    printf("export ETA_DIV_0=%f\n",eta_low);
    printf("export ETA_DIV_1=%f\n",eta_high);
  };


  // pt
  printf("\nexport PT_LOW=%f\n",pt_low);
  printf("export PT_HIGH=%f\n",pt_high);
  Double_t pt_width;
  if(pt_bins>0)
  {
    printf("export PT_BINS=%d\n",pt_bins);
    pt_width = (pt_high-pt_low)/pt_bins;
    for(Int_t i=0; i<=pt_bins; i++) printf("export PT_DIV_%d=%f\n",i,pt_low+i*pt_width);
  }
  else
  {
    // for en_bins=1 and eta_bins=1 -- 6 bin scheme
    ///*
    pt_bins=7;
    printf("export PT_BINS=%d\n",pt_bins);
    printf("export PT_DIV_0=%f\n",pt_low);
    printf("export PT_DIV_1=%f\n",1.5);
    printf("export PT_DIV_2=%f\n",2.5);
    printf("export PT_DIV_3=%f\n",3.5);
    printf("export PT_DIV_4=%f\n",4.75);
    printf("export PT_DIV_5=%f\n",6);
    printf("export PT_DIV_6=%f\n",8);
    printf("export PT_DIV_7=%f\n",pt_high);
    //*/
    // for en_bins=1 and eta_bins=1 -- 8 bin scheme
    /*
    pt_bins=8;
    printf("export PT_BINS=%d\n",pt_bins);
    printf("export PT_DIV_0=%f\n",pt_low);
    printf("export PT_DIV_1=%f\n",3);
    printf("export PT_DIV_2=%f\n",3.5);
    printf("export PT_DIV_3=%f\n",4);
    printf("export PT_DIV_4=%f\n",4.5);
    printf("export PT_DIV_5=%f\n",5.5);
    printf("export PT_DIV_6=%f\n",6.5);
    printf("export PT_DIV_7=%f\n",8);
    printf("export PT_DIV_8=%f\n",pt_high);
    */
  };

    
  // en
  printf("\nexport EN_LOW=%f\n",en_low);
  printf("export EN_HIGH=%f\n",en_high);
  Double_t en_width;
  if(en_bins>0)
  {
    printf("export EN_BINS=%d\n",en_bins);
    en_width = (en_high-en_low)/en_bins;
    for(Int_t i=0; i<=en_bins; i++) printf("export EN_DIV_%d=%f\n",i,en_low+i*en_width);
  }
  else
  {
    /*
    // for pt-dependnce for E<100 & E>100
    en_bins=2;
    printf("export EN_BINS=%d\n",en_bins);
    printf("export EN_DIV_0=%f\n",en_low);
    printf("export EN_DIV_1=%f\n",100);
    printf("export EN_DIV_2=%f\n",en_high);
    ///*
    // for pt_bins=1 and eta_bins=1
    en_bins=6;
    printf("export EN_BINS=%d\n",en_bins);
    printf("export EN_DIV_0=%f\n",en_low);
    printf("export EN_DIV_1=%f\n",25);
    printf("export EN_DIV_2=%f\n",50);
    printf("export EN_DIV_3=%f\n",75);
    printf("export EN_DIV_4=%f\n",100);
    printf("export EN_DIV_5=%f\n",150);
    printf("export EN_DIV_6=%f\n",en_high);
    */
    ///*
    en_bins=7;
    printf("export EN_BINS=%d\n",en_bins);
    printf("export EN_DIV_0=%f\n",en_low);
    printf("export EN_DIV_1=%f\n",20);
    printf("export EN_DIV_2=%f\n",28);
    printf("export EN_DIV_3=%f\n",36);
    printf("export EN_DIV_4=%f\n",50);
    printf("export EN_DIV_5=%f\n",65);
    printf("export EN_DIV_6=%f\n",80);
    printf("export EN_DIV_7=%f\n",en_high);
    //*/
  };
  printf("\nexport TRIGGER_TYPE=\"%s\"\n",trigger);
  printf("export MASS_CUT_TYPE=\"%s\"\n",cut_type);
  
  gSystem->RedirectOutput(0);
  char cat[128];
  sprintf(cat,".! cat %s",efile);
  printf("\n");
  gROOT->ProcessLine(cat);
  printf("\n%s built; source it by executing\n. env_bins.sh\n",efile);
};
