#!/bin/bash
# This file was generated by Bin_Splitter.C
# ** source this file while in this directory

export SPINDIR=$(pwd)

export PHI_LOW=-3.150000
export PHI_HIGH=3.150000
export PHI_BINS=10
export PHI_DIV_0=-3.150000
export PHI_DIV_1=-2.520000
export PHI_DIV_2=-1.890000
export PHI_DIV_3=-1.260000
export PHI_DIV_4=-0.630000
export PHI_DIV_5=0.000000
export PHI_DIV_6=0.630000
export PHI_DIV_7=1.260000
export PHI_DIV_8=1.890000
export PHI_DIV_9=2.520000
export PHI_DIV_10=3.150000

export ETA_LOW=2.500000
export ETA_HIGH=4.200000
export ETA_BINS=1
export ETA_DIV_0=2.500000
export ETA_DIV_1=4.200000

export PT_LOW=0.000000
export PT_HIGH=10.000000
export PT_BINS=7
export PT_DIV_0=0.000000
export PT_DIV_1=1.500000
export PT_DIV_2=2.500000
export PT_DIV_3=3.500000
export PT_DIV_4=4.750000
export PT_DIV_5=6.000000
export PT_DIV_6=8.000000
export PT_DIV_7=10.000000

export EN_LOW=0.000000
export EN_HIGH=100.000000
export EN_BINS=1
export EN_DIV_0=0.000000
export EN_DIV_1=100.000000

export TRIGGER_TYPE="All"
export MASS_CUT_TYPE="en"
export RP_SELECT="N"
