#!/bin/bash

echo "removing diagset/*.root in 5 seconds..."
sleep 5
rm -r diagset/*.root

ncondor="$(condor_config_val NUM_CPUS)"
if [ -z $ncondor ]; then
  echo "<X> WARNING: this is a memory intensive job! Are you sure you want condor"
  echo "    running with all available resources? You can limit the job by lowering"
  echo "    NUM_CPUS in /etc/condor/condor_config"
  echo "    - restart condor daeomon with condor_restart -startd && watch -n1 condor_status"
  echo ""
  echo " [sleeping for 10 seconds...]"
  sleep 10
else
  echo "<X> NOTE: condor will run a maximum of $ncondor simultaneous jobs"
fi

job="kincorr.bat"
> $job

echo "building batch file..."
echo "Executable = `which root`" >> $job
echo "Universe = vanilla" >> $job
echo "notification = never" >> $job
echo "getenv = True" >> $job
echo '+Experiment = "star"' >> $job
echo '+Job_Type = "cas"' >> $job
echo "" >> $job

log="logfiles"

# count number of defined RP triggers
# there is probably an easier way to do this...
f="tempo.C"
echo "void tempo() {" > $f
echo "gSystem->Load(\"src/RunData.so\");" >> $f
echo "TCUbits * tcu = new TCUbits();" >> $f
echo "gSystem->RedirectOutput(\"tempo.dat\",\"w\");" >> $f
echo "for(Int_t r=0; r<tcu->NRP; r++)" >> $f
echo "printf(\"%s\\n\",tcu->RPname(r));" >> $f
echo "gSystem->RedirectOutput(0);" >> $f
echo "};" >> $f
root -b -q tempo.C
echo "" >> tempo.dat
cat tempo.dat
nrp=$(cat tempo.dat | wc -l)
echo "nrp=$nrp"

pushd redset
ls RedOutputset*.root > LIST
popd


cnt=0

while read redfile; do
  while read line; do
    let cnt++
    echo "Arguments = -b -q DiagnosticsOne.C(\\\"${redfile}\\\",\\\"${line}\\\")" >> $job
    echo "Log    = ${log}/Diag.${redfile}.${line}.log" >> $job
    echo "Output = ${log}/Diag.${redfile}.${line}.out" >> $job
    echo "Error  = ${log}/Diag.${redfile}.${line}.err" >> $job
    echo "Queue" >> $job
    echo "" >> $job
  done < tempo.dat
done < redset/LIST


rm tempo.{dat,C}
rm redset/LIST

echo "Submitting $cnt jobs to condor"
condor_submit $job
