#!/bin/bash
# produces asymmetry plots for webpage for desired RP trigger

printstatus()
{
  sep="-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
  echo ""
  echo "$sep"
  echo "> > > > > RP_SELECT = $RP_SELECT < < < < <"
  echo "PT_BINS=$PT_BINS EN_BINS=$EN_BINS" 
  echo "PT_DIV_0=$PT_DIV_0 EN_DIV_0=$EN_DIV_0"
  echo "$sep"
  echo ""
}


phibins=10


if [ $# -ne 1 ]; then
  echo "usage: $0 [RP BOOLEAN NAME]"
  exit
fi
RP=$1

# en-dependence
root -b -q Bin_Splitter.C'('${phibins}',1,1,0)'
source env_bins.sh
export RP_SELECT=$RP
printstatus
./loop_PhiDists
./wait_for_condor
root -b -q toa_add.C
./asym_call_jets asym_plots/output_spinpwg_en_$RP
